brew "git"
brew "gh"
brew "volta"
brew "wget"
brew "nvim"
brew "tmux"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "zoxide"
brew "zsh-completions"
brew "diff-so-fancy"
brew "zsh-autosuggestions"

# cask "firefox"
# cask "google-chrome"
# cask "slack"
# cask "alacritty"
# cask "alfred"
# cask "font-inconsolata-g"
# cask "1password"
# cask "netnewswire"
# cask "karabiner-elements"
# cask "omnifocus"
# cask "rectangle-pro"
# cask "visual-studio-code"
# cask "insomnia"
# cask "qmk-toolbox"
# cask "focus"
