colorscheme Tomorrow-Night-Eighties
set guifont=Inconsolata:h12
set lines=60
set columns=200
set transparency=1
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set guioptions-=b
set guioptions-=m
set guioptions-=T
set guioptions-=r

