call pathogen#runtime_append_all_bundles()
colorscheme Tomorrow-Night-Eighties
set background=dark

set nowrap

" Move around splits with <c-hjkl>
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

let mapleader=","

" Edit files in directory of current file
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%

" List trailing whitespace
set listchars=tab:>-,trail:-
set list
