alias ll="ls -oGhA"
alias l="ls -G"
alias vi=vim

alias ..="cd .."

alias g="git status"
alias gc="git commit"
alias gl="git log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short"

alias tu='top -o cpu' # cpu
alias tm='top -o vsize' # memory

alias r="bundle exec rails"
