alias l="ls -oGhA"
alias wget="curl -O"

alias ..="cd .."

alias g="git status"
alias gc="git commit"
alias gl ="git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short"

alias tu='top -o cpu' # cpu
alias tm='top -o vsize' # memory

