if [ "$TERM" == "xterm" ]; then
    # No it isn't, it's gnome-terminal
    export TERM=xterm-256color
fi

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

source ~/dotfiles/bash/bash_env
source ~/dotfiles/bash/bash_config
source ~/dotfiles/bash/bash_aliases

source ~/dotfiles/bash/git-prompt.sh
source ~/dotfiles/bash/git-completion.sh
source ~/dotfiles/bash/bash_colors.sh
