if [ "$TERM" == "xterm" ]; then
    # No it isn't, it's gnome-terminal
    export TERM=xterm-256color
fi

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

source ~/dotfiles/bash/bash_env
source ~/dotfiles/bash/bash_config
source ~/dotfiles/bash/bash_aliases

source ~/dotfiles/bash/git-prompt.sh
source ~/dotfiles/bash/git-completion.sh
source ~/dotfiles/bash/bash_colors.sh
export PATH=/usr/local/bin:$PATH
