[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

source ~/bin/dotfiles/bash/bash_env
source ~/bin/dotfiles/bash/bash_config
source ~/bin/dotfiles/bash/bash_aliases
